FROM osrf/ros:humble-desktop

USER root

# Clone Isaac Sim ROS2 workspace
RUN git clone https://github.com/isaac-sim/IsaacSim-ros_workspaces.git /IsaacSim-ros_workspaces

WORKDIR /IsaacSim-ros_workspaces

RUN git submodule update --init --recursive

WORKDIR /IsaacSim-ros_workspaces/humble_ws

# Clone vision_msgs into src BEFORE building
WORKDIR /IsaacSim-ros_workspaces/humble_ws/src
RUN git clone -b humble https://github.com/ros-perception/vision_msgs.git

WORKDIR /IsaacSim-ros_workspaces/humble_ws

# Install dependencies and build
RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src --rosdistro=humble -y && \
    . /opt/ros/humble/setup.sh && \
    colcon build --symlink-install

# Source ROS2 and workspace in bashrc
RUN echo "source /opt/ros/humble/setup.bash" >> /etc/bash.bashrc
RUN echo "source /IsaacSim-ros_workspaces/humble_ws/install/local_setup.bash" >> /etc/bash.bashrc

WORKDIR /IsaacSim-ros_workspaces/humble_ws

ENTRYPOINT [ "/bin/bash" ]
CMD [ "-i" ]